######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 8 22:06:56 2016
######################################################################
QT -= gui core

TEMPLATE = app
TARGET = HttpClient
DEPENDPATH += .
INCLUDEPATH += .\

LIBS += -lsocket \
        -lpthread

# Input
HEADERS += 

SOURCES += HttpClient.cpp


