######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 8 22:06:56 2016
######################################################################
QT -= gui core

TEMPLATE = app
TARGET = RunProcessServer
DEPENDPATH += .
INCLUDEPATH += .\
                ../SocketLib

LIBS += -L../libs \
        -lsocket \
        -lpthread

HEADERS += RunProcess.h\

SOURCES += \
    SocketServer.cpp\
    RunProcess.cpp

