######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 8 07:56:47 2016
######################################################################
QT -= core gui

TEMPLATE = lib
TARGET = socket
CONFIG += staticlib


DESTDIR = ../libs

DEPENDPATH +=
INCLUDEPATH +=

# Input
HEADERS +=  SocketServ.h \
            SocketOperate.h
SOURCES +=  SocketServ.cpp
