######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 8 22:06:56 2016
######################################################################
QT -= gui core

TEMPLATE = app
TARGET = SocketClient
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -lpthread

HEADERS +=

SOURCES += \
    SocketClient.cpp
